name: 1 - Run action
run-name: By @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  test:
    if: ${{ github.actor == 'senad-d' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: '${{ secrets.PRIVATE_REPO }}'
          token: '${{ secrets.PRIVATE_TOKEN }}'
          persist-credentials: false
          ref: '${{ secrets.PRIVATE_BRANCH }}'

      - name: List variables
        run: |
          env | sort

      - name: Clear GitHub credentials
        run: |
          git config --global --unset credential.helper ""
          echo "GitHub credentials cleared!"