name: 1 - Run action
run-name: By @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  test:
    if: ${{ github.actor == 'senad-d' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: '${{ secrets.PRIVATE_REPO }}'
          token: '${{ secrets.PRIVATE_TOKEN }}'
          persist-credentials: false
          ref: '${{ secrets.PRIVATE_BRANCH }}'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_OPENID_ROLE }}
          role-duration-seconds: 30
          mask-aws-account-id: 'true'

      - name: Push files to S3
        run: |
          aws s3 sync ./ ${{ secrets.S3_BUCKET_NAME }} > /dev/null 2>&1 

      - name: Cleanup AWS Credentials
        if: ${{ always() }}
        run: |
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN
          echo "AWS credentials cleaned up."
